-- MySQL Script generated by MySQL Workbench
-- Tue Sep 10 18:58:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_final
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_final` DEFAULT CHARACTER SET utf8 ;
USE `projeto_final` ;

-- -----------------------------------------------------
-- Table `projeto_final`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_final`.`usuario` (
  `us_id` INT  AUTO_INCREMENT COMMENT 'id do usuario',
  `us_usuario` VARCHAR(45)  COMMENT 'nome do usuario',
  `us_senha` VARCHAR(70)  COMMENT 'Senha do usuario',
  `us_admin` int(11)  default 0 COMMENT 'tipo de usuario , existem 2 tipos de usuario , o (1)administrador e o (0)cliente',
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_final`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_final`.`cliente` (
  `cl_id` INT AUTO_INCREMENT comment 'id do cliente',
  `cl_nome` VARCHAR(45)  COMMENT 'nome do cliente',
  `cl_sobrenome` VARCHAR(100)  COMMENT 'sobrenome do cliente',
  `cl_data_nascimento` DATE  COMMENT 'data de nascimento',
  `cl_cpf` VARCHAR(11)  COMMENT 'CPF',
  `cl_telefone` VARCHAR(11)  COMMENT 'telefone',
  `cl_e-mail` VARCHAR(45)  COMMENT 'e-mail',
  `cl_rua` VARCHAR(45)  COMMENT 'nome da rua',
  `cl_numero` VARCHAR(45)  COMMENT 'numero da casa/ap',
  `cl_bairro` VARCHAR(45)  COMMENT 'bairro',
  `cl_cidade` VARCHAR(45)  COMMENT 'cidade',
  `cl_cep` VARCHAR(8)  COMMENT 'numero do cep',
  `us_id` INT ,
  PRIMARY KEY (`cl_id`),
  UNIQUE INDEX `cl_cpf` (`cl_cpf` ASC) VISIBLE,
  INDEX `fk_cliente_usuario_id` (`us_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`us_id`)
    REFERENCES `projeto_final`.`usuario` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_final`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_final`.`categoria` (
  `idcategoria` INT  AUTO_INCREMENT,
  `categoria` VARCHAR(45) ,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_final`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_final`.`produto` (
  `prod_id` INT  AUTO_INCREMENT,
  `prod_nome` VARCHAR(45)  COMMENT 'nome do produto',
  `prod_preco` FLOAT  COMMENT 'preço do produto',
  `prod_descricao` VARCHAR(100)  COMMENT 'informaçoes sobre o produto',
  `prod_rotulo` VARCHAR(80)  COMMENT 'rotulo do produto',
  `prod_quantidade` INT  DEFAULT 0 COMMENT 'quantidade de produto disponivel\n',
  `prod_destaque` INT  DEFAULT 0,
  `prod_carrosel` INT  DEFAULT 0,
  `idcategoria` INT ,
  PRIMARY KEY (`prod_id`),
  INDEX `fk_produto_categoria_idx` (`idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `projeto_final`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_final`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_final`.`pedido` (
  `vend_id` INT  AUTO_INCREMENT COMMENT 'id da venda',
  `vend_data` DATE  COMMENT 'data da venda',
  `cl_id` INT ,
  PRIMARY KEY (`vend_id`),
  INDEX `fk_pedido_cliente_idx` (`cl_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`cl_id`)
    REFERENCES `projeto_final`.`cliente` (`cl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_final`.`pedido_has_produto`
-- -----------------------------------------------------
CREATE TABLE `projeto_final`.`pedido_has_produto` (
`id_pedido` int not null AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_produto_prod_id_produto_idx` (`id_produto` ASC) ,
  CONSTRAINT `fk_produto_idx`
    FOREIGN KEY (`id_produto`)
    REFERENCES `projeto_final`.`produto` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;